### ISSUE TITLE
Clear Stage 

### ISSUE THREAD

**Issue by RealJonnW** [ermaccer/I2Hook#1]
I was wondering if you would be able to make an option to set the stage to be completely black/white. This would be better for capturing screenshots, to decrease load on pc when on practice, or ect. Just a suggestion I hope you can do. Thanks anyway

**Comment by ermaccer** [comment]
While I can't exactly do that, you can just use the empty map in stage modifier - that should load quickly.

**Comment by RealJonnW** [comment]
Ah ok thanks
