### ISSUE TITLE
Camera constantly changing

### ISSUE THREAD

**Issue by pluckywood** [ermaccer/I2Hook#4]
Sorry to bother,

I've installed the I2Hook and I cannot control the camera.  It's constantly switching to the regular camera and over the shoulder 3rd person.

I can open menus, but have no control of the camera.

Obviously something I'm doing wrong, but any help is appreciated.

**Comment by paschool** [comment]
im having this issue too, custom camera seems to be forcing to activate overtime

**Comment by ermaccer** [comment]
Either remove i2hook_user.ini or rebind the custom camera key in settings menu, it got corrupted somehow it seems.
